import { Inter } from 'next/font/google'
import './globals.css'
import Footer from "@/components/Footer/Footer.jsx"
import Cabecalho from "@/components/Cabecalho/Cabecalho.jsx"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lojinha FiapTech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Cabecalho/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
